# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-08 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fips', '0002_auto_20170309_0246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ref_code',
            field=models.CharField(default='7TgH3hfLabjB', max_length=12),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='User ID'),
        ),
    ]
