# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-08 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fips', '0003_auto_20170309_0400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ref_code',
            field=models.CharField(default='5Yrv8PEFBHFL', max_length=12),
        ),
    ]
