# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-10 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fips', '0004_auto_20170309_0500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ref_code',
            field=models.CharField(default='VNCSFoNNkC', max_length=10, verbose_name='Reference ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='referrer',
            field=models.TextField(help_text='identifier1-identifier2-identifier3', verbose_name='Referrers'),
        ),
    ]
