# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-13 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fips', '0007_auto_20170314_0210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ref_code',
            field=models.CharField(default='0hIHNyEAYO', max_length=10, verbose_name='Reference ID'),
        ),
    ]
