# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-14 00:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fips', '0008_auto_20170314_0210'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hits',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='ref_code',
            field=models.CharField(default='hMAKaxB7Nm', max_length=10, verbose_name='Reference ID'),
        ),
    ]
