# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-14 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fips', '0009_auto_20170314_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='hits',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='ref_code',
            field=models.CharField(default='W6QkRLrqb8', max_length=10, verbose_name='Reference ID'),
        ),
    ]
