# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-17 00:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fips', '0014_auto_20170317_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='upload_file',
            field=models.FileField(upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='ref_code',
            field=models.CharField(default='CxaPBR5Ill', max_length=10, verbose_name='Reference ID'),
        ),
    ]
