# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-17 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fips', '0015_auto_20170317_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='upload_file',
            field=models.FileField(upload_to='/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='ref_code',
            field=models.CharField(default='dmgu9jZOEy', max_length=10, verbose_name='Reference ID'),
        ),
    ]
