# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-20 18:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fips', '0018_auto_20170321_0322'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagecomment',
            options={'ordering': ['-created_date'], 'verbose_name_plural': 'Image Comments'},
        ),
        migrations.AlterField(
            model_name='imagecomment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='ref_code',
            field=models.CharField(default='iuWRa66YtV', max_length=10, verbose_name='Reference ID'),
        ),
    ]
