# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-20 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fips', '0019_auto_20170321_0325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ref_code',
            field=models.CharField(default='d14AM6AL7E', max_length=10, verbose_name='Reference ID'),
        ),
    ]
