# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-20 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fips', '0021_auto_20170321_0530'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagecomment',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='ref_code',
            field=models.CharField(default='whd2zKoVAz', max_length=10, verbose_name='Reference ID'),
        ),
    ]
