# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-21 01:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fips', '0028_auto_20170321_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ref_code',
            field=models.CharField(default='PsuThNanDw', max_length=10, verbose_name='Reference ID'),
        ),
    ]
